id: P001730
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:17:11.087332
source_metadata:
  id: bdr:W3CN6846
  title: བྱིས་སྒྲུང་འདམ་བསྒྲིག་རྣ་ཡི་དགའ་ཚལ།
  author: ''
  volumes:
    601f9d810221403082bb9e7e811f72c1:
      image_group_id: I3CN6848
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
