id: I23E454E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:03:16+00:00'
last_modified: '2022-06-07T14:13:44.583897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6846
  title: བྱིས་སྒྲུང་འདམ་བསྒྲིག་རྣ་ཡི་དགའ་ཚལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '8054':
      image_group_id: I3CN6848
      title: ''
      total_pages: 126
      order: 1
      base_file: 8054.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
